var class_c_a_d_lib_kernel_1_1_object_update_1_1_get_object_relation_type_by_name_completed_event_args =
[
    [ "Result", "class_c_a_d_lib_kernel_1_1_object_update_1_1_get_object_relation_type_by_name_completed_event_args.html#a421dfd334f7fb193d8da062bb7b383bc", null ]
];