var class_c_a_d_lib_kernel_1_1_object_update_1_1_get_object3_d_shapes_info_by_parent_id_completed_event_args =
[
    [ "Result", "class_c_a_d_lib_kernel_1_1_object_update_1_1_get_object3_d_shapes_info_by_parent_id_completed_event_args.html#a2cdf3ed3482702ae6affdbc8a56aa2f6", null ]
];