var class_c_a_d_lib_kernel_1_1_object_update_1_1_get_objects_id_by_name_and_parent_completed_event_args =
[
    [ "Result", "class_c_a_d_lib_kernel_1_1_object_update_1_1_get_objects_id_by_name_and_parent_completed_event_args.html#aa62dabbe19a1be8a850ff7a3ba57a90e", null ]
];