var class_c_a_d_lib_kernel_1_1_object_update_1_1_get_object_category_name_by_id_completed_event_args =
[
    [ "Result", "class_c_a_d_lib_kernel_1_1_object_update_1_1_get_object_category_name_by_id_completed_event_args.html#ab16956905eaa1435e2efa48c6a2aedca", null ]
];