var class_c_a_d_lib_kernel_1_1_object_update_1_1_get_objects_uid_by_parameters_value_completed_event_args =
[
    [ "Result", "class_c_a_d_lib_kernel_1_1_object_update_1_1_get_objects_uid_by_parameters_value_completed_event_args.html#ae491ff0d5b235ba71cf9b1ab2daa776c", null ]
];