var class_c_a_d_lib_kernel_1_1_object_update_1_1_get_lands_by_parent_object_by_page_completed_event_args =
[
    [ "Result", "class_c_a_d_lib_kernel_1_1_object_update_1_1_get_lands_by_parent_object_by_page_completed_event_args.html#a05d3e97ed34bdd6a2e94f054fe635bee", null ]
];