var namespace_c_s_project3_d_1_1_forms =
[
    [ "Expertise", "namespace_c_s_project3_d_1_1_forms_1_1_expertise.html", "namespace_c_s_project3_d_1_1_forms_1_1_expertise" ],
    [ "ListProject", "namespace_c_s_project3_d_1_1_forms_1_1_list_project.html", "namespace_c_s_project3_d_1_1_forms_1_1_list_project" ],
    [ "Viewer3D", "namespace_c_s_project3_d_1_1_forms_1_1_viewer3_d.html", "namespace_c_s_project3_d_1_1_forms_1_1_viewer3_d" ],
    [ "ClpProperties", "class_c_s_project3_d_1_1_forms_1_1_clp_properties.html", "class_c_s_project3_d_1_1_forms_1_1_clp_properties" ],
    [ "CVideoRecorderCodecSettings", "class_c_s_project3_d_1_1_forms_1_1_c_video_recorder_codec_settings.html", "class_c_s_project3_d_1_1_forms_1_1_c_video_recorder_codec_settings" ],
    [ "dbViewerModalDlg", "class_c_s_project3_d_1_1_forms_1_1db_viewer_modal_dlg.html", "class_c_s_project3_d_1_1_forms_1_1db_viewer_modal_dlg" ],
    [ "DocViewerForm", "class_c_s_project3_d_1_1_forms_1_1_doc_viewer_form.html", "class_c_s_project3_d_1_1_forms_1_1_doc_viewer_form" ],
    [ "EncodingOpenFileDialog", "class_c_s_project3_d_1_1_forms_1_1_encoding_open_file_dialog.html", "class_c_s_project3_d_1_1_forms_1_1_encoding_open_file_dialog" ],
    [ "FilterResult", "class_c_s_project3_d_1_1_forms_1_1_filter_result.html", "class_c_s_project3_d_1_1_forms_1_1_filter_result" ],
    [ "Form2D", "class_c_s_project3_d_1_1_forms_1_1_form2_d.html", "class_c_s_project3_d_1_1_forms_1_1_form2_d" ],
    [ "frmChooseParamDefs", "class_c_s_project3_d_1_1_forms_1_1frm_choose_param_defs.html", "class_c_s_project3_d_1_1_forms_1_1frm_choose_param_defs" ],
    [ "frmFileChoiseDlg", "class_c_s_project3_d_1_1_forms_1_1frm_file_choise_dlg.html", "class_c_s_project3_d_1_1_forms_1_1frm_file_choise_dlg" ],
    [ "frmHierEdit", "class_c_s_project3_d_1_1_forms_1_1frm_hier_edit.html", "class_c_s_project3_d_1_1_forms_1_1frm_hier_edit" ],
    [ "frmLinkToPropOrCode", "class_c_s_project3_d_1_1_forms_1_1frm_link_to_prop_or_code.html", "class_c_s_project3_d_1_1_forms_1_1frm_link_to_prop_or_code" ],
    [ "frmModelChangeLogParams", "class_c_s_project3_d_1_1_forms_1_1frm_model_change_log_params.html", "class_c_s_project3_d_1_1_forms_1_1frm_model_change_log_params" ],
    [ "frmObjectTableEditor", "class_c_s_project3_d_1_1_forms_1_1frm_object_table_editor.html", "class_c_s_project3_d_1_1_forms_1_1frm_object_table_editor" ],
    [ "frmWorkFilterDlg", "class_c_s_project3_d_1_1_forms_1_1frm_work_filter_dlg.html", "class_c_s_project3_d_1_1_forms_1_1frm_work_filter_dlg" ],
    [ "frmWorkResourceAssignment", "class_c_s_project3_d_1_1_forms_1_1frm_work_resource_assignment.html", "class_c_s_project3_d_1_1_forms_1_1frm_work_resource_assignment" ],
    [ "frmWorkSyncConflict", "class_c_s_project3_d_1_1_forms_1_1frm_work_sync_conflict.html", "class_c_s_project3_d_1_1_forms_1_1frm_work_sync_conflict" ],
    [ "HierarchySelection", "class_c_s_project3_d_1_1_forms_1_1_hierarchy_selection.html", "class_c_s_project3_d_1_1_forms_1_1_hierarchy_selection" ],
    [ "ModelCompareForm", "class_c_s_project3_d_1_1_forms_1_1_model_compare_form.html", "class_c_s_project3_d_1_1_forms_1_1_model_compare_form" ],
    [ "ModelDiagnosticSetupForm", "class_c_s_project3_d_1_1_forms_1_1_model_diagnostic_setup_form.html", "class_c_s_project3_d_1_1_forms_1_1_model_diagnostic_setup_form" ],
    [ "ModelRepresentationToolForm", "class_c_s_project3_d_1_1_forms_1_1_model_representation_tool_form.html", "class_c_s_project3_d_1_1_forms_1_1_model_representation_tool_form" ],
    [ "PhysPropsForm", "class_c_s_project3_d_1_1_forms_1_1_phys_props_form.html", "class_c_s_project3_d_1_1_forms_1_1_phys_props_form" ],
    [ "ProjectDocumentListUpdater", "class_c_s_project3_d_1_1_forms_1_1_project_document_list_updater.html", "class_c_s_project3_d_1_1_forms_1_1_project_document_list_updater" ],
    [ "ProjectDocumentsForm", "class_c_s_project3_d_1_1_forms_1_1_project_documents_form.html", "class_c_s_project3_d_1_1_forms_1_1_project_documents_form" ],
    [ "RelationsControl", "class_c_s_project3_d_1_1_forms_1_1_relations_control.html", "class_c_s_project3_d_1_1_forms_1_1_relations_control" ],
    [ "RelationsForm", "class_c_s_project3_d_1_1_forms_1_1_relations_form.html", "class_c_s_project3_d_1_1_forms_1_1_relations_form" ],
    [ "Vector2dPanel", "class_c_s_project3_d_1_1_forms_1_1_vector2d_panel.html", "class_c_s_project3_d_1_1_forms_1_1_vector2d_panel" ],
    [ "VideoRecorderControl", "class_c_s_project3_d_1_1_forms_1_1_video_recorder_control.html", "class_c_s_project3_d_1_1_forms_1_1_video_recorder_control" ],
    [ "VideoRecorderSettings", "class_c_s_project3_d_1_1_forms_1_1_video_recorder_settings.html", "class_c_s_project3_d_1_1_forms_1_1_video_recorder_settings" ],
    [ "WorkApplyOptionsDlg", "class_c_s_project3_d_1_1_forms_1_1_work_apply_options_dlg.html", "class_c_s_project3_d_1_1_forms_1_1_work_apply_options_dlg" ],
    [ "WorkLibSelectWorks", "class_c_s_project3_d_1_1_forms_1_1_work_lib_select_works.html", "class_c_s_project3_d_1_1_forms_1_1_work_lib_select_works" ],
    [ "WorkMgmtCustomAttribute", "class_c_s_project3_d_1_1_forms_1_1_work_mgmt_custom_attribute.html", "class_c_s_project3_d_1_1_forms_1_1_work_mgmt_custom_attribute" ],
    [ "WorksLibForm", "class_c_s_project3_d_1_1_forms_1_1_works_lib_form.html", "class_c_s_project3_d_1_1_forms_1_1_works_lib_form" ],
    [ "WorkStatusesForm", "class_c_s_project3_d_1_1_forms_1_1_work_statuses_form.html", "class_c_s_project3_d_1_1_forms_1_1_work_statuses_form" ],
    [ "TypeLoadProject", "namespace_c_s_project3_d_1_1_forms.html#aa877b4ae609503b250497a37b4243478", [
      [ "NONE", "namespace_c_s_project3_d_1_1_forms.html#aa877b4ae609503b250497a37b4243478ab50339a10e1de285ac99d4c3990b8693", null ],
      [ "Update", "namespace_c_s_project3_d_1_1_forms.html#aa877b4ae609503b250497a37b4243478a06933067aafd48425d67bcb01bba5cb6", null ],
      [ "Copy", "namespace_c_s_project3_d_1_1_forms.html#aa877b4ae609503b250497a37b4243478a5fb63579fc981698f97d55bfecb213ea", null ]
    ] ]
];